[mypy]
exclude = src/sieve/datamodel/sieve_models\.py

[mypy-sieve.datamodel.sieve_models]
ignore_errors = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-typer.*]
ignore_missing_imports = True

[mypy-linkml.*]
ignore_missing_imports = True

[mypy-linkml_runtime.*]
ignore_missing_imports = True

